# Prometheus Configuration for Advanced Notification System

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'notification-system'
    environment: 'production'

rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Notification Service Instances
  - job_name: 'notification-service'
    static_configs:
      - targets: 
        - 'notification-service-1:5000'
        - 'notification-service-2:5000'
        - 'notification-service-3:5000'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    params:
      format: ['prometheus']

  # Node Exporter for System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets:
        - 'node-exporter-1:9100'
        - 'node-exporter-2:9100'
        - 'node-exporter-3:9100'
    scrape_interval: 15s

  # MongoDB Exporter
  - job_name: 'mongodb-exporter'
    static_configs:
      - targets:
        - 'mongodb-exporter:9216'
    scrape_interval: 30s

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets:
        - 'redis-exporter:9121'
    scrape_interval: 15s

  # Nginx Exporter
  - job_name: 'nginx-exporter'
    static_configs:
      - targets:
        - 'nginx-exporter:9113'
    scrape_interval: 15s

  # Blackbox Exporter for External Service Monitoring
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://api.sendgrid.com/v3/user/profile
        - https://api.twilio.com/2010-04-01/Accounts.json
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Application Health Checks
  - job_name: 'notification-health'
    metrics_path: /health
    static_configs:
      - targets:
        - 'notification-service-1:5000'
        - 'notification-service-2:5000'
        - 'notification-service-3:5000'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Custom Application Metrics
  - job_name: 'notification-custom-metrics'
    static_configs:
      - targets:
        - 'notification-service-1:5000'
        - 'notification-service-2:5000'
        - 'notification-service-3:5000'
    metrics_path: '/api/v1/metrics'
    scrape_interval: 30s
    params:
      format: ['prometheus']

  # Queue Metrics (Redis-based)
  - job_name: 'notification-queues'
    static_configs:
      - targets:
        - 'notification-service-1:5000'
    metrics_path: '/api/v1/queue-metrics'
    scrape_interval: 15s

  # External Service Response Times
  - job_name: 'external-services'
    static_configs:
      - targets:
        - 'notification-service-1:5000'
    metrics_path: '/api/v1/external-service-metrics'
    scrape_interval: 60s

# Remote Write Configuration (Optional - for long-term storage)
remote_write:
  - url: "https://prometheus-remote-write.yourdomain.com/api/v1/write"
    basic_auth:
      username: "prometheus"
      password: "your_remote_write_password"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500

# Storage Configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 50GB
    path: /prometheus/data
    wal-compression: true